config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'

  root 'horses#index'

  resources :horses
  resources :tags, only: [:destroy]

  get "horses/tag/:tag"  => "horses#tag"
  get "horses/tag"  => "horses#tag"

  get "tags/new" => "tags#new"
  post "tags" => "tags#create"

end

app/models/horse.rb
class Horse < ActiveRecord::Base
  has_and_belongs_to_many :tags
end

app/models/horses_tags.rb
class HorsesTags < ActiveRecord::Base
  belongs_to :horse
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :horses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/horses_controller.rb
FlickRaw.api_key=ENV["API_KEY"]
FlickRaw.shared_secret=ENV["API_SECRET"]

class HorsesController < ApplicationController

  def index
  @horses = Horse.all.order('breed ASC')

 end

 def new
  @horse = Horse.new
 end

 def create
  @horse = Horse.create(horse_params)
    # render :json => params
     params[:horse][:tags].each do |tag_id|
      @horse.tags << Tag.find(tag_id) unless tag_id.blank?
     end
    redirect_to horses_path
  end

  def show
    @horse = Horse.find(params[:id])
    @search = @horse.breed
    list = flickr.photos.search :text => @search + ' horse', :sort => 'relevance'

    # results = list.map do |photo|
    #    "https:/farm3.static.flickr.com/#{photo["server"]}/" "#{photo["id"]}_" "#{photo["secret"]}_n.jpg"
    # end
    # @result = results.sample

    @results = list.map do |photo|
      [FlickRaw.url(photo),
        FlickRaw.url(photo)]
    end


  end

  def destroy
    @horse = Horse.find(params[:id])
    @horse.destroy
    redirect_to horses_path
  end

  def edit
    @horse = Horse.find(params[:id])
  end

  def tag
    tag = Tag.find_by_name(params[:tag])
    @horses =  tag ? tag.horses : []
  end

  def update
    @tags = Tag.all
    @horse = Horse.find(params[:id])
    Horse.update(@horse, horse_params)
    @horse.tags.clear
    params[:horse][:tag_ids].each do |tag_ids|
    @horse.tags << Tag.find(tag_ids) unless tag_ids.blank?
  end

    redirect_to @horse

    # tags.each do |tags_id|
    #   @horse.tags << Tag.find_or_create_by({name:tag_id}) unless tag_id.blank?
    # end

  end


  private

  def horse_params
    horse_params = params.require(:horse).permit(:breed, :origin, :bloodtype)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController


  def index
    @tags = Tag.all.order('name ASC')
  end

  def create
    @tags = Tag.new(tag_params)
    @tags.save
    redirect_to tags_index_path
  end

  def new
    @tags = Tag.new
    @horse = Horse.all
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_index_path
  end

private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/horses/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Details</h1>
  <div class ="well col-md-6 col-md-offset-3">
      <div class="form-group">
        <%= bootstrap_form_for @horse do |f| %>

        <%= f.text_field :breed, :placeholder => "Horse Name", :class => "form-control"%>
        <%= f.text_field :origin, :placeholder => "Horse Description", :class => "form-control text-area" %>
         <%= f.text_field :bloodtype, :placeholder => "Horse Bloodtype", :class => "form-control text-area" %>
         <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
        <%= f.submit :class => "btn btn-tag btn-lg center-block"%>
        <% end %>

        <div class="backlink"><%= link_to "&larr; Back to List".html_safe, horses_path %></div>
      </div>
  </div>
</div>

app/views/horses/index.html.erb
<div class="container">
  <h1 class="text-center">Horse Breeds</h1>
  <br>
  <div class="text-center" id="addnewindex"><%= link_to 'Add a New Breed', new_horse_path, :class => "btn btn-tag btn-lg" %></div>
  <br>
  <% @horses.each do |p| %>
  <div class="well col-sm-10 col-sm-offset-1" id="horsebreeds">

    <div class="col-sm-6">
      <h2 id="breed"><%= link_to p.breed, p %></h2>
      <p><strong>Origin: </strong> <%= p.origin %></p>
      <p><strong>Bloodtype: </strong> <%= p.bloodtype %></p>
      <p><%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-tag-main btn-md" %> &nbsp <%= link_to 'Edit', [:edit, p], :class => "btn btn-tag-main btn-md"%></p>
    </div>

    <div class="col-sm-6">
      <% @search = p.breed %>
      <% list = flickr.photos.search :text => @search + 'horse', :sort => 'relevance' %>
      <% results = list.map do |photo| %>
      <%  "https://farm3.static.flickr.com/#{photo["server"]}/" "#{photo["id"]}_" "#{photo["secret"]}_n.jpg" %>
      <% end %>
      <% @result = results.sample %>

      <!-- <img src="<%= @result %>"> -->
      <%= image_tag("#{@result}") %>
    </div>
  </div>
  <% end %>
</div>

app/views/horses/new.html.erb
<div class="container">
    <h1 class="text-center">Add a New Horse Breed</h1>
    <br>
    <br>
    <div class="well col-md-6 col-md-offset-3" id="newbreed">
  <div class="form-group form-group-lg">
    <%= bootstrap_form_for @horse do |f| %>
    <%= f.text_field :breed, :placeholder =>"Enter the Breed" %>
    <%= f.text_field :origin, :placeholder =>"Enter the Breed's Place of Origin" %>
    <%= f.text_field :bloodtype, :placeholder =>"Enter Bloodtpye (Hot ,Cold, Warm)" %>
    <%= f.collection_check_boxes :tags, Tag.all, :id, :name %>
    <%= f.submit "Submit new Horse Breed", class: "btn btn-tag btn-lg center-block" %>
    <% end %>
    <div><%= link_to "&larr; Back to List".html_safe, horses_path %></div>
  </div>
</div>
</div>

app/views/horses/show.html.erb
<div class="container">

  <div class="well col-sm-12 col-sm-offset-1" id="showtext">
    <h1 class="text-center" id="showhead"><%= @horse.breed %></h1>
    <div class="col-md-6">
      <p><strong>Origin: </strong> <%= @horse.origin %></p>
      <p><strong>Bloodtype: </strong> <%= @horse.bloodtype %></p>
      <div class="btn-group">
        <% @horse.tags.each do |tag| %>
        <%=button_to tag.name, "/horses/tag/#{tag.name}", method: :get, :class => "btn-tag btn-md" %>
        <%end%>
      </div>
      <br>
      <br>
      <div class="backlink"><%= link_to "&larr; back to list".html_safe, horses_path %></div>
    </div>

    <div class="col-md-6" id="showphotos">
      <div id="myCarousel" class="carousel slide" data-ride="carousel" class="carousel slide">
        <div class="carousel-inner" role="listbox">
          <% @results[0..25].each_with_index do |item, index| %>
          <div class="item <% if index == 0 %>active<% end %>">
            <%= link_to image_tag(item.first), item.last, :class => "hover" %>
          </div>
          <% end %>
        </div>
        <!-- Left and right controls -->
        <div>
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/horses/tag.html.erb
<div class="container">
  <h1 class="text-center" id="viewbreedtag">View Breeds by Discipline Tag: <%= params[:tag] %></h1>

  <div class="col-md-10 col-md-offset-1">
    <br>
    <br>
    <div class="well col-md-10 col-md-offset-1">
      <% @horses.each do |horse| %>
      <%= link_to horse.breed, horse, :class => "btn btn-tag btn-lg" %>
      <% end %>
      <br>
      <br>
      <br>
      <div class="backlink"><%= link_to "&larr; back to list".html_safe, horses_path %></div><br/>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HorseBreedApp</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Merriweather+Sans:400,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700|Playfair+Display+SC:700,400' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <link href='//fonts.googleapis.com/css?family=Josefin+Sans:100,300,400|Raleway:100,400,200,300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>

<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-header">



      <a class="brand pull-left" href="/"> <%= image_tag("horsehead.png", :id => "logo") %> HobbyHorse</a>


    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="/" class="">View Breeds</a></li>
        <li class="active"><%= link_to 'Add Breed', new_horse_path %> </li>
        <li class="active"><%= link_to 'View Disciplines', tags_index_path %> </li>
        <li class="active"><%= link_to 'Add Discipline', tags_new_path %> </li>

      </ul>
    </div>
  </div>
</nav>


<div class"container">
<%= yield %>
</div>


</body>
</html>

app/views/tags/index.html.erb
<div class="container">

<h1 class="text-center">Discipline Tags</h1>
<br>

  <div class="text-center" id="addnewindex"><%= link_to 'Breed List', horses_path, :class => "btn btn-tag btn-lg" %> &nbsp <%= link_to 'Add New Discipline Tag', tags_new_path, :class => "btn btn-tag btn-lg" %></div>

<br>
<br>
  <div class="well col-md-10 col-md-offset-1">

<div class="tagindexdivs">
    <% @tags.each do |tag| %>
    <%#button_to tag.name, taghorse_path(tag.name), method: :get, :class => "btn btn-xs" %>
    <button class="btn btn-tag btn-md" id="tags"><%= link_to tag.name, "/horses/tag/#{tag.name}" %><%= link_to '', tag, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn glyphicon glyphicon-remove-circle" %></button>

    <%end%>
</div>




  </div>

</div>

app/views/tags/new.html.erb
<div class="container">

      <h1 class="text-center">Add a Discipline Tag</h1>
      <br>
  <div class ="well col-md-6 col-md-offset-3">


      <div class="form-group">

       <%= bootstrap_form_for @tags do |f| %>

       <%= f.text_field :name, :placeholder => "Add Discipline Name" %><br/>

       <%= f.submit :class => "btn btn-tag btn-lg center-block" %>

       <% end %>

   </div>
 </div>
 </div>